### ISSUE TITLE
About the parameter `--valid_data` in the training command mentioned in README.md

### ISSUE THREAD

**Issue by lexiaoyuan** [roatienza/deep-text-recognition-benchmark#16]
Hi, thanks for your work!
When training, should the parameter `--valid_data` in the command be followed by `data_lmdb_release/validation`? But I found it written as `data_lmdb_release/evaluation` in README.md. 
Looking forward to your reply!

**Comment by roatienza** [comment]
In ViTSTR, the `evaluation` split was used to choose the best performing model. So, that was argument that follows `--valid-data` . The alternative is to use `validation` split but that will not necessarily find the best performing model on the target test dataset.
