### ISSUE TITLE
How to draw the attention map of ViTSTR?

### ISSUE THREAD

**Issue by lexiaoyuan** [roatienza/deep-text-recognition-benchmark#24]
Hello, thank you very much for being able to open the source code, it is a very rewarding work.
I am a graduate student and I want to do a little bit of my own experiment based on ViTSTR. Now I want to draw an attention map similar to the one shown in Fig. 9 of your paper, can you give me some help? Thank you very much!

**Comment by roatienza** [comment]
Hi, Attention rollout: https://github.com/jacobgil/vit-explain
