### ISSUE TITLE
Question about [GO] and [s]

### ISSUE THREAD

**Issue by sparrow0629** [roatienza/deep-text-recognition-benchmark#26]
Hi, thanks for your amazing work.
When you convert the label using class TokenLabelConverter, you pad the label with [GO] which is ignored during loss calculation, however in paper, figure 4 shows that the label is padded with [s].
Does this make any difference on accuracy?

**Comment by roatienza** [comment]
`[GO]` is the start token. After the predicted text, succeeding tokens are spaces that are represented by `[s]`.
